-- Borrar base de datos  si no existe
DROP DATABASE IF EXISTS VENTAS;

-- Crear base de datos
CREATE DATABASE VENTAS;

-- USar base de datos
USE VENTAS;

-- Crear tabla cliente
CREATE TABLE CUSTOMER(
	CUSTNO			CHAR(8),
    CUSTFNAME		VARCHAR(50) NOT NULL,
    CUSTLNAME		VARCHAR(50) NOT NULL,
    CUSTCITY		VARCHAR(40),
    CUSTSTATE		CHAR(2),
    CUSTZIP			CHAR(10),
    CUSTBAL			DECIMAL(3,2),
    CONSTRAINT CUSTNO PRIMARY KEY (CUSTNO)
);

-- Mostrar tabla cliente
DESCRIBE CUSTOMER;

-- Crear tabla Empleado
CREATE TABLE EMPLOYEE(
	EMPNO			CHAR(8),
    EMPFNAME		VARCHAR(50) NOT NULL,
    EMPLNAME		VARCHAR(50) NOT NULL,
    EMPPHONE		CHAR(9),
    EMPEMAIL		VARCHAR(40) NOT NULL,
    CONSTRAINT EMPNO PRIMARY KEY (EMPNO)
);

-- Mostrar tabla empleado
DESCRIBE EMPLOYEE;

-- Crear tabla Order table
CREATE TABLE ODRTBL(
	ORDNO			CHAR(8),
    ORDDATE			DATE,
    CUSTNO			CHAR(8),
    EMPNO			CHAR(8) not null,
    CONSTRAINT ORDNO PRIMARY KEY (ORDNO)
);

-- Mostrar tabla Order table
DESCRIBE ODRTBL;

-- Relación entre las tablas ODRTBL - Cliente
ALTER TABLE ODRTBL ADD CONSTRAINT ORDTBL_CUSTOMER_CUSTNO FOREIGN KEY (CUSTNO) REFERENCES CUSTOMER(CUSTNO);

-- Relación entre las tablas ODRTBL - Empleado
ALTER TABLE ODRTBL ADD CONSTRAINT ORDTBL_EMPLOYEE_EMPNO FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE(EMPNO);